### ISSUE TITLE
Test suite failed to run: cannot find module '../header' from 'header.js'

### ISSUE THREAD

**Issue by jimmyandrade** [multei/web#14]
**Given** we are on `master` branch and all dependencies are installed with `npm install`
**When** running `npm test` or `jest`,
**Then** we find this:

```
FAIL src/components/__tests__/header.js
  ● Test suite failed to run

    Cannot find module '../header' from 'header.js'
```

```js
      1 | import React from "react"
      2 | import renderer from "react-test-renderer"
    > 3 | import Header from "../header"
        | ^
      4 | describe("Header", () => {
      5 |   it("renders correctly", () => {
      6 |     const tree = renderer
```

```
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (src/components/__tests__/header.js:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.951s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
##[error]Process completed with exit code 1.
```

**Comment by jimmyandrade** [comment]
@all-contributors please add @adalbertomaia for code
