### ISSUE TITLE
🐛 [Bug] Cypress GitHub action failing

### ISSUE THREAD

**Issue by jimmyandrade** [multei/web#75]
## Description

Sometimes End-to-end test with Cypress action are failing because it seems that application is not running. We need to check it and fix it.

## Steps to reproduce the behavior:

1. Check pull request #73;
2. Look for end-to-end test at https://github.com/multei/web/pull/73/checks;
3. Click on **Cypress run** to expand.

## Expected behavior

**End-to-end tests** action should be completed with success.

## Actual behavior

```
Cypress could not verify that this server is running:

  > http://localhost:8000/

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
Error: The process '/usr/local/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1188:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1171:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1071:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

## Additional context

```
Current runner version: '2.165.2'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'cypress-io/github-action@v1'

actions/checkout@v2
  with:
    repository: multei/web
    token: ***
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false

    clean: true
    fetch-depth: 1
    lfs: false
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: multei/web
Working directory is '/home/runner/work/web/web'
/usr/bin/git version
git version 2.25.1
Deleting the contents of '/home/runner/work/web/web'
/usr/bin/git init /home/runner/work/web/web
Initialized empty Git repository in /home/runner/work/web/web/.git/
/usr/bin/git remote add origin https://github.com/multei/web
/usr/bin/git config --local gc.auto 0
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +741e69d34878766c696e48150d087e111d6c950b:refs/remotes/origin/renovate/testing-library-cypress-6.x
remote: Enumerating objects: 172, done.        
remote: Total 172 (delta 4), reused 119 (delta 2), pack-reused 0
From https://github.com/multei/web
 * [new ref]         741e69d34878766c696e48150d087e111d6c950b -> origin/renovate/testing-library-cypress-6.x
/usr/bin/git checkout --progress --force -B renovate/testing-library-cypress-6.x refs/remotes/origin/renovate/testing-library-cypress-6.x
Switched to a new branch 'renovate/testing-library-cypress-6.x'
Branch 'renovate/testing-library-cypress-6.x' set up to track remote branch 'renovate/testing-library-cypress-6.x' from 'origin'.
/usr/bin/git log -1
commit 741e69d34878766c696e48150d087e111d6c950b
Author: Renovate Bot <bot@renovateapp.com>
Date:   Thu Mar 12 23:34:34 2020 +0000

    chore(deps): update dependency @testing-library/cypress to v6
Removed matchers: 'checkout-git'

> cypress@4.1.0 postinstall /home/runner/work/web/web/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 4.1.0)

[23:35:47]  Unzipped Cypress        [title changed]
[23:35:47]  Unzipped Cypress        [completed]
[23:35:47]  Finishing Installation  [started]
[23:35:47]  Finished Installation   /home/runner/.cache/Cypress/4.1.0 [title changed]
[23:35:47]  Finished Installation   /home/runner/.cache/Cypress/4.1.0 [completed]

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

added 3181 packages in 44.861
```

**Comment by jimmyandrade** [comment]
Ropening because I closed by mistake (and PR #122 is not yet passing)

@all-contributors please add @thomazmz and @ruandev as code

**Comment by jimmyandrade** [comment]
@all-contributors now please add @ruandev as code

**Comment by jimmyandrade** [comment]
Ropening because I closed by mistake (and last commit did not passed):
https://github.com/multei/web/runs/569641077
